/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.view;

import java.util.List;

import br.edu.ifsp.control.ClientControl;
import br.edu.ifsp.control.IControl;
import br.edu.ifsp.model.Client;
import br.edu.ifsp.view.model.ClientTableModel;

/**
 *
 * @author cg147862
 */
public class ClientForm extends javax.swing.JFrame {

	private static final long serialVersionUID = 1729824683017383505L;

	/**
	 * Creates new form ClientForm
	 */
	public ClientForm() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		actionPanel = new javax.swing.JPanel();
		addButton = new javax.swing.JButton();
		updateButton = new javax.swing.JButton();
		deleteButton = new javax.swing.JButton();
		queryButton = new javax.swing.JButton();
		dataPanel = new javax.swing.JPanel();
		nomeLabel = new javax.swing.JLabel();
		nomeField = new javax.swing.JTextField();
		nascimentoLabel = new javax.swing.JLabel();
		nascimentoField = new javax.swing.JFormattedTextField();
		confirmationPanel = new javax.swing.JPanel();
		salvarButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();
		clientTable = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowOpened(java.awt.event.WindowEvent evt) {
				onOpen(evt);
			}
		});

		actionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));
		actionPanel.setName("acaoPanel"); // NOI18N

		addButton.setText("Incluir");
		addButton.setName("incluirButton"); // NOI18N
		addButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				incluirButtonActionPerformed(evt);
			}
		});

		updateButton.setText("Atualizar");
		updateButton.setName("atualizarButton"); // NOI18N
		updateButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				atualizarButtonActionPerformed(evt);
			}
		});

		deleteButton.setText("Excluir");
		deleteButton.setName("excluirButton"); // NOI18N

		queryButton.setText("Consultar");
		queryButton.setName("consultarButton"); // NOI18N

		javax.swing.GroupLayout acoesPanelLayout = new javax.swing.GroupLayout(actionPanel);
		actionPanel.setLayout(acoesPanelLayout);
		acoesPanelLayout.setHorizontalGroup(acoesPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(acoesPanelLayout.createSequentialGroup().addContainerGap()
						.addGroup(acoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(queryButton, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		acoesPanelLayout
				.setVerticalGroup(acoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(acoesPanelLayout.createSequentialGroup().addContainerGap()
								.addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(queryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		dataPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Cliente"));
		dataPanel.setEnabled(false);
		dataPanel.setName("dadosPanel"); // NOI18N

		nomeLabel.setText("Nome Completo");
		nomeLabel.setEnabled(false);
		nomeLabel.setName("nomeLabel"); // NOI18N

		nomeField.setEnabled(false);
		nomeField.setName("nameField"); // NOI18N

		nascimentoLabel.setText("Data Nascimento");
		nascimentoLabel.setEnabled(false);
		nascimentoLabel.setName("nascimentoLabel"); // NOI18N

		nascimentoField.setFormatterFactory(
				new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
		nascimentoField.setEnabled(false);
		nascimentoField.setName("nascimentoField"); // NOI18N

		javax.swing.GroupLayout dadosPanelLayout = new javax.swing.GroupLayout(dataPanel);
		dataPanel.setLayout(dadosPanelLayout);
		dadosPanelLayout
				.setHorizontalGroup(
						dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(dadosPanelLayout.createSequentialGroup().addContainerGap()
										.addGroup(dadosPanelLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(nomeField)
												.addGroup(dadosPanelLayout.createSequentialGroup()
														.addGroup(dadosPanelLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(nomeLabel).addComponent(nascimentoLabel)
																.addComponent(nascimentoField,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 146,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(0, 0, Short.MAX_VALUE)))
										.addContainerGap()));
		dadosPanelLayout
				.setVerticalGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(dadosPanelLayout.createSequentialGroup().addContainerGap().addComponent(nomeLabel)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(nascimentoLabel)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(nascimentoField, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		confirmationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
		confirmationPanel.setName("confirmacaoPanel"); // NOI18N

		salvarButton.setText("Salvar");
		salvarButton.setEnabled(false);
		salvarButton.setName("salvaButton"); // NOI18N

		cancelButton.setText("Cancelar");
		cancelButton.setEnabled(false);
		cancelButton.setName("cancelarButton"); // NOI18N
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelarButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout confirmacaoPanelLayout = new javax.swing.GroupLayout(confirmationPanel);
		confirmationPanel.setLayout(confirmacaoPanelLayout);
		confirmacaoPanelLayout.setHorizontalGroup(confirmacaoPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmacaoPanelLayout.createSequentialGroup()
						.addContainerGap()
						.addGroup(confirmacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(salvarButton, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap()));
		confirmacaoPanelLayout
				.setVerticalGroup(confirmacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(confirmacaoPanelLayout.createSequentialGroup().addContainerGap()
								.addComponent(salvarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		clientTable.setModel(new ClientTableModel(new String[] { "Código Cliente", "Nome Completo", "Data Nascimento" },
				new Object[][] {}));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(dataPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(actionPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(confirmationPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addGroup(layout.createSequentialGroup()
								.addComponent(dataPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
						.addGroup(layout.createSequentialGroup()
								.addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(confirmationPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}

	private void atualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void incluirButtonActionPerformed(java.awt.event.ActionEvent evt) {
		this.enableDataPanel(true);
	}

	private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {
		this.enableDataPanel(false);
	}

	private void onOpen(java.awt.event.WindowEvent evt) {
		IControl<Client> control = new ClientControl();

		List<Client> clientList = control.list();

		ClientTableModel model = (ClientTableModel)this.clientTable.getModel();

		for (Client c : clientList)
			model.addRow(c);
	}

	private void enableDataPanel(boolean enabled) {
		this.dataPanel.setEnabled(enabled);
		this.nomeLabel.setEnabled(enabled);
		this.nomeField.setEnabled(enabled);
		this.nascimentoLabel.setEnabled(enabled);
		this.nascimentoField.setEnabled(enabled);

		this.clientTable.setEnabled(!enabled);
		this.clientTable.setRowSelectionAllowed(!enabled);

		this.actionPanel.setEnabled(!enabled);
		this.addButton.setEnabled(!enabled);
		this.queryButton.setEnabled(!enabled);
		this.deleteButton.setEnabled(!enabled);
		this.updateButton.setEnabled(!enabled);

		this.confirmationPanel.setEnabled(enabled);
		this.salvarButton.setEnabled(enabled);
		this.cancelButton.setEnabled(enabled);
	}

	// Variables declaration - do not modify
	private javax.swing.JPanel actionPanel;
	private javax.swing.JButton updateButton;
	private javax.swing.JButton cancelButton;
	private javax.swing.JTable clientTable;
	private javax.swing.JPanel confirmationPanel;
	private javax.swing.JButton queryButton;
	private javax.swing.JPanel dataPanel;
	private javax.swing.JButton deleteButton;
	private javax.swing.JButton addButton;
	private javax.swing.JFormattedTextField nascimentoField;
	private javax.swing.JLabel nascimentoLabel;
	private javax.swing.JTextField nomeField;
	private javax.swing.JLabel nomeLabel;
	private javax.swing.JButton salvarButton;
	// End of variables declaration
}
